"""Remove quantity and avg_cost, add initial_investment and purchase_date to holdings

Revision ID: c919bccfadcc
Revises: 
Create Date: 2025-11-20 23:43:14.551060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c919bccfadcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('starting_price', sa.Float(), nullable=False))
    op.add_column('holdings', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.drop_column('holdings', 'quantity')
    op.drop_column('holdings', 'avg_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('avg_cost', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.add_column('holdings', sa.Column('quantity', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True))
    op.drop_column('holdings', 'purchase_date')
    op.drop_column('holdings', 'initial_investment')
    # ### end Alembic commands ###
